### ISSUE TITLE
Documentation update: Jyväskylä use case

### ISSUE THREAD

**Issue by jkesanie** [ATTX-project/ATTX-project.github.io#44]
#### Description

See title. 

#### DoD

Updated docs.

#### Testing

Peer-review

**Comment by jkesanie** [comment]
Added all the information we have at the moment.
https://attx-project.github.io/Use-case-Jyvaskyla.html

**Comment by blankdots** [comment]
Added a table of contents, fixed  OA acronym meaning.
Added link to University of Jyväskylä library.

Divide the user stories based on different types of users: admin, anonymous, regular,  etc.
A bit confusing how a use case can be complementary to a data set "ATTX use case can be seen as complementary to the VIRTA data set"
Data source: PURE - missing link ?
TUTKA - missing link ?
TUHAT - missing link ?

Maybe have fields such as "dc.identifier.other" as code `dc.identifier.other`

**Comment by jkesanie** [comment]
Made couple of changes based on review comments. I did not do any styling related changes, because the document is still a draft.
