### ISSUE TITLE
article: PyGradle demo

### ISSUE THREAD

**Issue by jkesanie** [ATTX-project/ATTX-project.github.io#6]
#### Description

Modify and extend the current github.io page so that it can be read as a independent post. 
For example: add examples, give context. 
#### DoD
New version of the io-page.
#### Testing
Peer-review

**Comment by blankdots** [comment]
Repositories and article (which was committed to dev) are ready for review.
https://github.com/blankdots/pygradle-jsonld-cli
https://github.com/blankdots/pygradle-falcon-api

**Comment by jkesanie** [comment]
I just fixed one formatting issue. Looks good.
