### ISSUE TITLE
Automate generation of HTML pages

### ISSUE THREAD

**Issue by blankdots** [ATTX-project/ATTX-project.github.io#7]
#### Description
Automate the generation of HTML pages as a Jenkins task
#### DoD
Jenkins task that commits and pushes changes to git.
#### Testing
Peer review

**Comment by blankdots** [comment]
Example: https://github.com/JozoVilcek/gitbook-example that makes use of this library https://github.com/srs/gradle-node-plugin

**Comment by blankdots** [comment]
Extended the https://github.com/JozoVilcek/gitbook-example  to fit our purpose, @jkesanie should we make it public ?
Jenkins job available although it requires configuration to run a scheduled basis. Found a fix for connecting to github from jenkins in the response of http://stackoverflow.com/a/18936804

**Comment by blankdots** [comment]
Repository created: https://github.com/ATTX-project/gradle-pullrequest-builder

**Comment by jkesanie** [comment]
Seems to work nicely! Putting this to done.
